import json
import time

from google import genai
from google.genai import types

from config import GEMINI_API_KEY


INPUT_FILE = "tests/answer_evaluation_results.json"
OUTPUT_FILE = "tests/gemini_quality_results.json"

MODEL_NAME = "gemini-3.6-flash"

# Gemini free tier reported a limit of 5 requests/minute.
REQUEST_INTERVAL = 13


client = genai.Client(api_key=GEMINI_API_KEY)


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def judge_answer(result):

    question = result["question"]
    answer = result.get("answer", "")
    context = result.get("context", "")
    expected_sources = result.get("expected_sources", [])
    expected_pages = result.get("expected_pages", [])
    citations = result.get("citations", [])

    prompt = f"""
You are evaluating an answer generated by a Retrieval-Augmented Generation
(RAG) system.

Evaluate the generated answer using the retrieved context as the primary
evidence.

Do not use outside knowledge to fill gaps.

QUESTION:
{question}

GENERATED ANSWER:
{answer}

RETRIEVED CONTEXT:
{context}

EXPECTED SOURCES:
{expected_sources}

EXPECTED PAGES:
{expected_pages}

CITATIONS:
{citations}

Evaluate four dimensions.

1. CORRECTNESS

Score from 1 to 5:

1 = Incorrect or substantially wrong
2 = Mostly incorrect; major factual problems
3 = Partially correct
4 = Mostly correct; minor issues
5 = Fully correct

2. GROUNDEDNESS

Score from 1 to 5:

1 = Claims are essentially unsupported by the context
2 = Mostly unsupported
3 = Partially supported
4 = Mostly supported
5 = Fully supported by the context

3. COMPLETENESS

Score from 1 to 5:

1 = Does not answer the question
2 = Answers very little
3 = Partially answers the question
4 = Covers most important parts
5 = Fully answers the question

4. HALLUCINATION

Determine whether the answer contains information that is unsupported,
misattributed, invented, or incorrectly derived from the retrieved context.

severity:

1 = Very minor unsupported detail
2 = Small unsupported or misattributed claim
3 = Several unsupported claims or significant unsupported information
4 = Major unsupported information
5 = Answer is largely fabricated or unrelated

Important:

- Do not penalize different wording from the context.
- Do not require word-for-word reproduction.
- Distinguish missing information from incorrect information.
- Identify unsupported or misattributed claims.
- Evaluate the generated answer itself.
- Give concise reasons.

Return ONLY valid JSON:

{{
    "correctness": {{
        "score": 1,
        "reason": "..."
    }},
    "groundedness": {{
        "score": 1,
        "reason": "..."
    }},
    "completeness": {{
        "score": 1,
        "reason": "..."
    }},
    "hallucination": {{
        "detected": false,
        "severity": 1,
        "reason": "..."
    }}
}}
"""

    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0,
            response_mime_type="application/json",
        ),
    )

    return json.loads(response.text)


def is_successful_evaluation(item):

    evaluation = item.get("answer_evaluation")

    if not evaluation:
        return False

    try:
        return (
            evaluation["correctness"]["score"] is not None
            and evaluation["groundedness"]["score"] is not None
            and evaluation["completeness"]["score"] is not None
            and evaluation["hallucination"]["detected"] is not None
        )
    except (KeyError, TypeError):
        return False


def main():

    source_results = load_json(INPUT_FILE)

    # Load previous evaluations if they exist.
    try:
        previous_results = load_json(OUTPUT_FILE)
    except FileNotFoundError:
        previous_results = []

    # Keep only genuinely successful previous evaluations.
    completed = {}

    for item in previous_results:
        if is_successful_evaluation(item):
            completed[item["question"]] = item

    print("=" * 70)
    print("GEMINI ANSWER QUALITY EVALUATION")
    print("=" * 70)

    print(f"Source questions: {len(source_results)}")
    print(f"Already evaluated successfully: {len(completed)}")

    evaluated_results = []

    for result in source_results:

        question = result["question"]

        # ---------------------------------------------------------
        # SKIP SUCCESSFULLY EVALUATED QUESTIONS
        # ---------------------------------------------------------

        if question in completed:

            evaluated_results.append(completed[question])

            print()
            print("-" * 70)
            print(f"SKIPPED: {question}")
            print("Already evaluated successfully.")

            continue

        print()
        print("-" * 70)
        print(f"EVALUATING: {question}")

        context = result.get("context", "")

        print(f"Context length: {len(context)}")

        # ---------------------------------------------------------
        # MISSING ANSWER
        # ---------------------------------------------------------

        if not result.get("answer"):

            evaluation = {
                "correctness": {
                    "score": 1,
                    "reason": "No generated answer was available."
                },
                "groundedness": {
                    "score": 1,
                    "reason": "No generated answer was available."
                },
                "completeness": {
                    "score": 1,
                    "reason": "No generated answer was available."
                },
                "hallucination": {
                    "detected": False,
                    "severity": 1,
                    "reason": "No answer was available to evaluate."
                }
            }

            evaluated_result = {
                "question": question,
                "answer": result.get("answer"),
                "context": context,
                "expected_sources": result.get("expected_sources", []),
                "expected_pages": result.get("expected_pages", []),
                "citations": result.get("citations", []),
                "answer_evaluation": evaluation,
            }

            evaluated_results.append(evaluated_result)
            save_json(OUTPUT_FILE, evaluated_results)

            continue

        # ---------------------------------------------------------
        # MISSING CONTEXT
        # ---------------------------------------------------------

        if not context:

            print("WARNING: Retrieved context is empty.")
            print("Skipping Gemini evaluation.")

            continue

        # ---------------------------------------------------------
        # WAIT BETWEEN REQUESTS
        # ---------------------------------------------------------

        if evaluated_results:
            print(
                f"Waiting {REQUEST_INTERVAL} seconds "
                "before Gemini request..."
            )
            time.sleep(REQUEST_INTERVAL)

        # ---------------------------------------------------------
        # GEMINI REQUEST
        # ---------------------------------------------------------

        try:

            evaluation = judge_answer(result)

            print(
                f"Correctness: "
                f"{evaluation['correctness']['score']}/5"
            )

            print(
                f"Groundedness: "
                f"{evaluation['groundedness']['score']}/5"
            )

            print(
                f"Completeness: "
                f"{evaluation['completeness']['score']}/5"
            )

            print(
                f"Hallucination: "
                f"{evaluation['hallucination']['detected']} "
                f"(severity "
                f"{evaluation['hallucination']['severity']}/5)"
            )

        except Exception as e:

            print(f"Gemini evaluation failed: {e}")
            print("This question will remain unevaluated.")

            # IMPORTANT:
            # Do NOT save a failed evaluation as a completed result.
            # That allows this script to retry it on the next run.

            continue

        # ---------------------------------------------------------
        # SAVE SUCCESSFUL EVALUATION
        # ---------------------------------------------------------

        evaluated_result = {
            "question": question,
            "answer": result.get("answer"),
            "context": context,
            "expected_sources": result.get("expected_sources", []),
            "expected_pages": result.get("expected_pages", []),
            "citations": result.get("citations", []),
            "answer_evaluation": evaluation,
        }

        evaluated_results.append(evaluated_result)

        save_json(
            OUTPUT_FILE,
            evaluated_results
        )

        print("Evaluation saved.")

    # -------------------------------------------------------------
    # FINAL SUMMARY
    # -------------------------------------------------------------

    successful = [
        item
        for item in evaluated_results
        if is_successful_evaluation(item)
    ]

    print()
    print("=" * 70)
    print("CURRENT SUMMARY")
    print("=" * 70)

    print(
        f"Successfully evaluated: "
        f"{len(successful)}/{len(source_results)}"
    )

    if successful:

        correctness_scores = [
            item["answer_evaluation"]["correctness"]["score"]
            for item in successful
        ]

        groundedness_scores = [
            item["answer_evaluation"]["groundedness"]["score"]
            for item in successful
        ]

        completeness_scores = [
            item["answer_evaluation"]["completeness"]["score"]
            for item in successful
        ]

        hallucinations = [
            item["answer_evaluation"]["hallucination"]["detected"]
            for item in successful
        ]

        print(
            f"Average correctness: "
            f"{sum(correctness_scores) / len(correctness_scores):.2f}/5"
        )

        print(
            f"Average groundedness: "
            f"{sum(groundedness_scores) / len(groundedness_scores):.2f}/5"
        )

        print(
            f"Average completeness: "
            f"{sum(completeness_scores) / len(completeness_scores):.2f}/5"
        )

        print(
            f"Hallucination detected: "
            f"{sum(hallucinations)}/{len(hallucinations)}"
        )

    remaining = len(source_results) - len(successful)

    print(
        f"Remaining questions: {remaining}"
    )

    print()
    print(f"Results saved to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()